### ISSUE TITLE
Need to update doctrine dependencies

### ISSUE THREAD

**Issue by PoetikDragon** [API-Skeletons/doctrine-data-fixture#2]
Unable to install via composer in a new Laminas project with Doctrine due to a conflict in dependencies versions. This package calls for `doctrine/doctrine-module ^1.2.0 || ^2.1.0` while the current DoctrineORMModule for Laminas requires `doctrine/doctrine-module ^4.0`.

**Comment by TomHAnderson** [comment]
This is a simple fix and the change to Doctrine Module 4.0 is backwards compatible.  It would be nice if you'd make this change and submit a pull request.  I can prioritize someone else being proactive and reviewing and approving their pull request but I can't prioritize fixing something which isn't affecting me today.

**Comment by PoetikDragon** [comment]
I forked the repo and changed the dependencies, but after installing ran into other errors with the return statement for executing a command, same as this other similar package:

https://github.com/codeedu/zendexpr-doctrine-fixture/issues/1

**Comment by TomHAnderson** [comment]
The Command error was a one line fix.  There is a new build now.  Thanks for reporting.

https://github.com/API-Skeletons/doctrine-data-fixture/pull/3/files
